About soiree
VamsiRao/ph2_RSVP pull request #10
Opened 2017-07-18 12:23 UTC by VamsiRao

2017-07-18 12:55 UTC, Shubham2301 requested changes

2017-07-18 12:55 UTC, Shubham2301 commented on public/wp-content/themes/ColoredCow/landing.php
> +			<h5 class="soiree-header font-marcellus">Soiree</h5>
use css for font-sizing. in place of h5

2017-07-18 12:55 UTC, Shubham2301 commented on public/wp-content/themes/ColoredCow/landing.php
> +		<div class="col-xs-12 col-md-6 font-marcellus event-col">
what naming the class as font-marcellus??

2017-07-18 12:55 UTC, Shubham2301 commented on public/wp-content/themes/ColoredCow/landing.php
> +								</div>
whats inside this div?

2017-07-18 12:55 UTC, Shubham2301 commented on public/wp-content/themes/ColoredCow/src/scss/fonts.scss
> +.font-inherit{
Let's not use this. Read about inheritance in scss

2017-07-18 12:55 UTC, Shubham2301 commented on public/wp-content/themes/ColoredCow/src/scss/style.scss
> +	margin-top:30px;
you can extend the font class here

2017-07-18 12:55 UTC, Shubham2301 commented on public/wp-content/themes/ColoredCow/src/scss/style.scss
> +.event-date-loc{
let's use more explanatory class name

2017-07-19 05:28 UTC, VamsiRao commented on public/wp-content/themes/ColoredCow/landing.php
> +								</div>
for space

2017-07-19 12:56 UTC, merged